# Author:   Donzy.xu
# CreateTime:   2022/9/13 - 23:37
# FileName:  update.py

import maya.cmds as cmds

ctl = [u'R_LipUpper_02_SewBrige_CTL',
       u'R_LipUpper_01_SewBrige_CTL',
       u'R_LipUpper_00_SewBrige_CTL',
       u'R_LipLower_02_SewBrige_CTL',
       u'R_LipLower_01_SewBrige_CTL',
       u'R_LipLower_00_SewBrige_CTL',
       u'R_LipConner_00_SewBrige_CTL',
       u'M_LipUpper_00_SewBrige_CTL',
       u'M_LipLower_00_SewBrige_CTL',
       u'L_LipUpper_02_SewBrige_CTL',
       u'L_LipUpper_01_SewBrige_CTL',
       u'L_LipUpper_00_SewBrige_CTL',
       u'L_LipLower_02_SewBrige_CTL',
       u'L_LipLower_01_SewBrige_CTL',
       u'L_LipLower_00_SewBrige_CTL',
       u'L_LipConner_00_SewBrige_CTL',
       u'M_HeadLower_CTL',
       u'M_HeadUpper_CTL',
       u'R_SocketOuter_00_Part_CTL',
       u'R_SocketInner_00_Part_CTL',
       u'R_LidOuter_00_Part_CTL',
       u'R_LidInner_00_Part_CTL',
       u'L_SocketOuter_00_Part_CTL',
       u'L_SocketInner_00_Part_CTL',
       u'M_UpperLattice_CTL',
       u'M_JawLattice_CTL',
       u'M_MiddleLattice_CTL',
       u'L_LidOuter_00_Part_CTL',
       u'L_LidInner_00_Part_CTL',
       u'L_SocketInner_00_CTL',
       u'R_LidLower_01_CTL',
       u'L_LidLower_01_CTL',
       u'R_LidLower_02_CTL',
       u'R_SocketUpper_00_CTL',
       u'L_LidLower_02_CTL',
       u'R_SocketLower_00_CTL',
       u'R_LidInner_00_CTL',
       u'R_LidLower_00_CTL',
       u'R_LidUpper_01_CTL',
       u'L_LidUpper_00_CTL',
       u'R_SocketInner_00_CTL',
       u'R_SocketLower_02_CTL',
       u'R_SocketUpper_01_CTL',
       u'R_SocketUpper_02_CTL',
       u'R_SocketLower_01_CTL',
       u'L_SocketLower_02_CTL',
       u'L_LidUpper_02_CTL',
       u'L_SocketUpper_01_CTL',
       u'R_LidUpper_02_CTL',
       u'R_SocketOuter_00_CTL',
       u'L_SocketLower_01_CTL',
       u'R_LidUpper_00_CTL',
       u'L_SocketOuter_00_CTL',
       u'L_Cheek_00_CTL',
       u'L_SocketUpper_02_CTL',
       u'L_LidUpper_01_CTL',
       u'L_SocketLower_00_CTL',
       u'R_Cheek_00_CTL',
       u'R_LidOuter_00_CTL',
       u'L_LidInner_00_CTL',
       u'L_LidOuter_00_CTL',
       u'L_SocketUpper_00_CTL',
       u'L_LidLower_00_CTL']
cmds.hide(ctl)
