    def updateDG(self):
        self.renderStatus = False
        self.shape_class.refresh_plug.asInt()

        cSkin = self.shape_class.cSkin

        if not cSkin or cSkin.DATA.rawPoints_output is None:
            return

        # 在这里统一读取 UI 最新属性，并同步给后端黑板！
        self.shape_class.sync_ui_state_to_blackboard()

        # region Topology
        _cache = self._get_topology_index_buffers(cSkin)
        if _cache:
            (
                self._cached_solidIdx_mgr,
                self._cached_wireIdx_mgr,
                self._cached_pointIdx_mgr,
                self._cached_vertex_count,
            ) = _cache

        # endregion

        self._cached_raw_points_mgr = cSkin.DATA.rawPoints_output

        # region Color
        weights2D_mgr, target_idx, is_mask = cSkin.DATA.active_paint_target
        self._cached_weights_1d = None
        if weights2D_mgr is not None and weights2D_mgr.view is not None:
            mv_2d = weights2D_mgr.view
            # 获取列数 (即 influences_count，如果是遮罩则为 1)
            cols = mv_2d.shape[1] if len(mv_2d.shape) > 1 else 1
            # 越界保护
            safe_idx = max(0, min(target_idx, cols - 1))
            mv_1d_flat = mv_2d.cast("B").cast("f")
            self._cached_weights_1d = mv_1d_flat[safe_idx::cols]
        self._cached_paintMask = is_mask
        self._cached_render_mode = cSkin.DATA.render_mode
        self._cached_c_wire = cSkin.DATA.color_wire
        self._cached_c_point = cSkin.DATA.color_point
        self._cached_c_mask_remapA = cSkin.DATA.color_mask_remapA
        self._cached_c_mask_remapB = cSkin.DATA.color_mask_remapB
        self._cached_c_weights_remapA = cSkin.DATA.color_weights_remapA
        self._cached_c_weights_remapB = cSkin.DATA.color_weights_remapB
        self._cached_c_brush_remapA = cSkin.DATA.color_brush_remapA
        self._cached_c_brush_remapB = cSkin.DATA.color_brush_remapB
        # endregion

        # Brush DATA
        self._cached_hit_state = cSkin.DATA.brush_hit_state
        self.renderStatus = True

    def populateGeometry(self, requirements, renderItems, data):
        """
        由于显示色是根据顶点来进行渐变的，
        我们无法让点，边，线显示不同颜色
        所以我们申请了三分点的数据放在内存中
        -----------------
        0-1,第一份点数据,填充模型点位置信息              填充颜色A
        1-2,第二份点数据,同上填充和上面一模一样的位置信息,填充颜色B
        2-3,第三份点数据,同上填充和上面一模一样的位置信息,填充颜色C
        -----------------
        然后需要让模型显示出 面，边，点，
        需要申请新的缓存，用来填充模型结构
        比如 绘制 `面`
        [[0,1,2], # face1,三个点的index
            [1,2,3], # face2,三个点的index
            [2,3,4]] # face3,三个点的index
        显卡会去 `kPosition` 填充的数据中寻找这些点，绘制出面
        并且使用 `kColor` 中的颜色来渲染面的颜色
        当我绘制 边的时候
        我可以用第二遍填充的点数据来绘制，只要填充的index对应第二遍填充的index
        比如 绘制 `边`
        [[10,11], # face1,三个点的index
            [11,12], # face2,三个点的index
            [12,13]] # face3,三个点的index
        这样显卡会在`kPosition`中寻找对应的index，
        并且使用 `kColor` 对应的index颜色来绘制边。
        比如 绘制 `点`同理
        """
        print("populateGeometry")
        if not self.renderStatus:
            return

        N = self._cached_vertex_count
        points_mgr = self._cached_raw_points_mgr

        # ==========================================
        # 1. 填充顶点缓冲 (位置 & 颜色)
        # ==========================================
        for req in requirements.vertexRequirements():
            if req.semantic == omr.MGeometry.kPosition:
                # """ `POINTS` """
                if points_mgr and points_mgr.ptr_addr:
                    vtx_buf = data.createVertexBuffer(req)
                    vtx_addr = vtx_buf.acquire(N * 3, True)
                    if vtx_addr:
                        print('提交点成功')
                        # """
                        # 默认申请 `acquire(N,True)` 返回`[x,y,z] * N`的缓存空间, 类型是`float`
                        # 我们需要 `面，点，边` 颜色不同,  所以申请三倍的空间 `N*3`,
                        # MAYA会给我们一个 `[x,y,z] * N*3` 的缓存空间。
                        # """
                        # fmt:off
                        # 连续三次硬拷贝 (面、线、点共用同一套坐标)
                        stride = N * 12 # len([x,y,z]) * N * 4 bytes
                        #               Target Addr              Source Addr                Length
                        ctypes.memmove( vtx_addr              ,    points_mgr.ptr_addr,       stride )
                        ctypes.memmove( vtx_addr + stride     ,    points_mgr.ptr_addr,       stride )
                        ctypes.memmove( vtx_addr + stride * 2 ,    points_mgr.ptr_addr,       stride )
                        vtx_buf.commit( vtx_addr )
                        
                        # fmt:on
            # ==========================================
            # 🎨 填充顶点缓冲 (颜色)
            # ==========================================
            elif req.semantic == omr.MGeometry.kColor:
                # """ `Color` """
                color_buf = data.createVertexBuffer(req)
                color_addr = color_buf.acquire(N * 3, True)
                if color_addr:
                    # 使用 `CMemoryManager` 快速映射显存
                    color_view = CMemoryManager.from_ptr(color_addr, "f", (N * 3, 4)).view
                    print(color_view)
                    # ==================================
                    # 🎨  面颜色 (0~N): 权重梯度
                    # ==================================
                    if self._cached_weights_1d is not None:
                        # Mask Mode
                        if self._cached_paintMask:
                            cColor.render_gradient(self._cached_weights_1d, color_view[0:N], self._cached_c_mask_remapA, self._cached_c_mask_remapB)
                        # Alpha Mode
                        elif self._cached_render_mode == 1:
                            cColor.render_gradient(self._cached_weights_1d, color_view[0:N], self._cached_c_weights_remapA, self._cached_c_weights_remapB)
                        # heatmap Mode
                        else:
                            cColor.render_heatmap(self._cached_weights_1d, color_view[0:N])
                    # None Weights color
                    else:
                        cColor.render_fill(color_view[0:N], (0.0, 0.0, 1.0, 1.0))

                    # ==================================
                    # 🎨 线颜色 (N~2N)
                    # ==================================
                    cColor.render_fill(color_view[N : 2 * N], self._cached_c_wire)

                    # ==================================
                    # 🎨 笔刷点颜色 (2N~3N)
                    # ==================================
                    hit_state = self._cached_hit_state
                    if hit_state and hit_state.hit_count > 0:
                        cColor.render_brush_gradient(
                            color_view[2 * N : 3 * N],
                            hit_state.hit_indices_mgr.view,
                            hit_state.hit_weights_mgr.view,
                            hit_state.hit_count,
                            self._cached_c_brush_remapA,
                            self._cached_c_brush_remapB,
                        )
                    color_buf.commit(color_addr)

        # ==========================================
        #  填充topology缓冲 (index偏移)
        # ==========================================
        for item in renderItems:
            item_name = item.name()

            # --- 面索引 (0 偏移) ---
            if item_name == "WeightSolidItem" and self._cached_solidIdx_mgr:
                mgr = self._cached_solidIdx_mgr
                num_indices = mgr.view.nbytes // 4
                i_buf = data.createIndexBuffer(omr.MGeometry.kUnsignedInt32)
                i_addr = i_buf.acquire(num_indices, True)
                if i_addr:
                    ctypes.memmove(i_addr, mgr.ptr_addr, num_indices * 4)  # 直接拷贝
                    i_buf.commit(i_addr)
                    item.associateWithIndexBuffer(i_buf)

            # --- 线索引 (N 偏移) ---
            elif item_name == "WeightWireItem" and self._cached_wireIdx_mgr:
                mgr = self._cached_wireIdx_mgr
                num_indices = mgr.view.nbytes // 4
                i_buf = data.createIndexBuffer(omr.MGeometry.kUnsignedInt32)
                i_addr = i_buf.acquire(num_indices, True)
                if i_addr:
                    offset_indices = array.array("I", (x + N for x in mgr.view))
                    addr, _ = offset_indices.buffer_info()
                    ctypes.memmove(i_addr, addr, num_indices * 4)
                    i_buf.commit(i_addr)
                    item.associateWithIndexBuffer(i_buf)

            # --- 笔刷点索引 (2N 偏移) ---
            elif item_name == "BrushDebugPoints":
                hit_state = self._cached_hit_state
                hit_count = hit_state.hit_count
                if hit_state and (hit_count > 0):
                    i_buf = data.createIndexBuffer(omr.MGeometry.kUnsignedInt32)
                    i_addr = i_buf.acquire(hit_count, True)
                    if i_addr:
                        brush_indices = array.array("I", (x + (2 * N) for x in hit_state.hit_indices_mgr.view))
                        addr, _ = brush_indices.buffer_info()
                        ctypes.memmove(i_addr, addr, hit_count * 4)
                        i_buf.commit(i_addr)
                        item.associateWithIndexBuffer(i_buf)