from UTILS.compounds import matrixConstraint
from maya import cmds
a = {'Root_M': 'pelvis',
     'HipPart1_L': 'thigh_twist_01_l',
     'HipPart2_L': 'thigh_twist_02_l',
     'Knee_L': 'calf_l',
     'KneePart1_L': 'calf_twist_02_l',
     'KneePart2_L': 'calf_twist_01_l',
     'Hip_L': 'thigh_l',
     'Ankle_L': 'foot_l',
     'Toes_L': 'ball_l',
     'FootThumbFinger1_L': 'bigtoe_01_l',
     'FootThumbFinger2_L': 'bigtoe_02_l',
     'FootIndexFinger1_L': 'indextoe_01_l',
     'FootIndexFinger2_L': 'indextoe_02_l',
     'FootMiddleFinger1_L': 'middletoe_01_l',
     'FootMiddleFinger2_L': 'middletoe_02_l',
     'FootRingFinger1_L': 'ringtoe_01_l',
     'FootRingFinger2_L': 'ringtoe_02_l',
     'FootPinkyFinger1_L': 'littletoe_01_l',
     'FootPinkyFinger2_L': 'littletoe_02_l',
     'Spine1_M': 'spine_01',
     'Spine2_M': 'spine_02',
     'Spine3_M': 'spine_03',
     'Chest_M': 'spine_04',
     'ChestEnd_M': 'spine_05',
     'Scapula_L': 'clavicle_l',
     'Shoulder_L': 'upperarm_l',
     'ShoulderPart1_L': 'upperarm_twist_01_l',
     'ShoulderPart2_L': 'upperarm_twist_02_l',
     'Elbow_L': 'lowerarm_l',
     'ElbowPart1_L': 'lowerarm_twist_02_l',
     'ElbowPart2_L': 'lowerarm_twist_01_l',
     'Wrist_L': 'hand_l',
     'ThumbFinger1_L': 'thumb_01_l',
     'ThumbFinger2_L': 'thumb_02_l',
     'ThumbFinger3_L': 'thumb_03_l',
     'IndexFingerRoot_L': 'index_metacarpal_l',
     'IndexFinger1_L': 'index_01_l',
     'IndexFinger2_L': 'index_02_l',
     'IndexFinger3_L': 'index_03_l',
     'MiddleFingerRoot_L': 'middle_metacarpal_l',
     'MiddleFinger1_L': 'middle_01_l',
     'MiddleFinger2_L': 'middle_02_l',
     'MiddleFinger3_L': 'middle_03_l',
     'RingFingerRoot_L': 'ring_metacarpal_l',
     'RingFinger1_L': 'ring_01_l',
     'RingFinger2_L': 'ring_02_l',
     'RingFinger3_L': 'ring_03_l',
     'PinkyFingerRoot_L': 'pinky_metacarpal_l',
     'PinkyFinger1_L': 'pinky_01_l',
     'PinkyFinger2_L': 'pinky_02_l',
     'PinkyFinger3_L': 'pinky_03_l',
     'Neck_M': 'neck_01',
     'Neck1_M': 'neck_02',
     'Head_M': 'head',
     'HipPart1_R': 'thigh_twist_01_r',
     'HipPart2_R': 'thigh_twist_02_r',
     'Knee_R': 'calf_r',
     'KneePart1_R': 'calf_twist_02_r',
     'KneePart2_R': 'calf_twist_01_r',
     'Hip_R': 'thigh_r',
     'Ankle_R': 'foot_r',
     'Toes_R': 'ball_r',
     'FootThumbFinger1_R': 'bigtoe_01_r',
     'FootThumbFinger2_R': 'bigtoe_02_r',
     'FootIndexFinger1_R': 'indextoe_01_r',
     'FootIndexFinger2_R': 'indextoe_02_r',
     'FootMiddleFinger1_R': 'middletoe_01_r',
     'FootMiddleFinger2_R': 'middletoe_02_r',
     'FootRingFinger1_R': 'ringtoe_01_r',
     'FootRingFinger2_R': 'ringtoe_02_r',
     'FootPinkyFinger1_R': 'littletoe_01_r',
     'FootPinkyFinger2_R': 'littletoe_02_r',
     'Scapula_R': 'clavicle_r',
     'Shoulder_R': 'upperarm_r',
     'ShoulderPart1_R': 'upperarm_twist_01_r',
     'ShoulderPart2_R': 'upperarm_twist_02_r',
     'Elbow_R': 'lowerarm_r',
     'ElbowPart1_R': 'lowerarm_twist_02_r',
     'ElbowPart2_R': 'lowerarm_twist_01_r',
     'Wrist_R': 'hand_r',
     'ThumbFinger1_R': 'thumb_01_r',
     'ThumbFinger2_R': 'thumb_02_r',
     'ThumbFinger3_R': 'thumb_03_r',
     'IndexFingerRoot_R': 'index_metacarpal_r',
     'IndexFinger1_R': 'index_01_r',
     'IndexFinger2_R': 'index_02_r',
     'IndexFinger3_R': 'index_03_r',
     'MiddleFingerRoot_R': 'middle_metacarpal_r',
     'MiddleFinger1_R': 'middle_01_r',
     'MiddleFinger2_R': 'middle_02_r',
     'MiddleFinger3_R': 'middle_03_r',
     'RingFingerRoot_R': 'ring_metacarpal_r',
     'RingFinger1_R': 'ring_01_r',
     'RingFinger2_R': 'ring_02_r',
     'RingFinger3_R': 'ring_03_r',
     'PinkyFingerRoot_R': 'pinky_metacarpal_r',
     'PinkyFinger1_R': 'pinky_01_r',
     'PinkyFinger2_R': 'pinky_02_r',
     'PinkyFinger3_R': 'pinky_03_r'}

for k, v in a.items():
    if cmds.objExists(k) and cmds.objExists(v):
        con = matrixConstraint(mo=0)
        cmds.select(con.inputOffsetMatrix)
        offsetMatrix = [-1.0, 0.0, 0.0, 0.0,
                         0.0, 0.0, 1.0, 0.0,
                         0.0, 1.0, 0.0, 0.0,
                         0.0, 0.0, 0.0, 1.0,
                         ]
        cmds.getAttr(con.inputOffsetMatrix)
        cmds.setAttr(con.inputOffsetMatrix,)
